<?php

use Drupal\simple_sitemap\Entity\SimpleSitemapInterface;
use Drupal\group\Entity\GroupContent;

/**
 * Alter the generated link data before a sitemap is saved.
 *
 * This hook gets invoked for every sitemap chunk generated.
 *
 * @param array &$links
 *   Array containing links generated for each path to be indexed.
 * @param SimpleSitemapInterface $sitemap
 *   Sitemap entity.
 */
function lalg_utilities_simple_sitemap_links_alter(array &$links, SimpleSitemapInterface $sitemap) {
 
  foreach ($links as $key => $link) {
	if (isset($link['meta']['entity_info'])) {
		if ($link['meta']['entity_info']['entity_type'] == "group") {
			$gid = $link['meta']['entity_info']['id'];
			$archived = \Drupal::service('lalg_utilities.group_tasks')->isGroupArchived($gid);
			$hidden = \Drupal::service('lalg_utilities.group_tasks')->isGroupHidden($gid);
			if ($archived || $hidden) {
			  unset($links[$key]);
			}
		}
	}
  }
}

/**
 * Disable the Contact Details Text field - but still keep visible for now.
 *
 */
function lalg_utilities_form_alter(&$form, &$form_state, $form_id) {

  if ($form_id == 'group_group_edit_form') {
	  $form['field_contact_details']['#disabled'] = TRUE;
  }
}